/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/blue_archive_highlander_twins_nozomi__hikari.glb --transform 
Files: public/models/blue_archive_highlander_twins_nozomi__hikari.glb [10.6MB] > C:\Users\tomis\Documents\TestWebXR\blue_archive_highlander_twins_nozomi__hikari-transformed.glb [1.12MB] (89%)
Author: Taprieiko (https://sketchfab.com/Taprieiko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-archive-highlander-twins-nozomi-hikari-369c4c7b484e48cd9cd3bd73848d625b
Title: Blue Archive: Highlander Twins, Nozomi & Hikari
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blue_archive_highlander_twins_nozomi__hikari-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_7.geometry} material={materials.Outline_Hair} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.BGStuff} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.HikariFacev4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Hikari_Halo} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Nozomi_Halo} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Nozomifacev4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Train_Uni} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Emotes} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['HikariFacev4-Whites']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Hikari_Hair} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['NozomiFacev4-Whites']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Nozomi_Hair} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Outline_Generic} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Outline_Hair} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Skin_Outline} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Train_Uni-Transparent']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.bodyv3} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/blue_archive_highlander_twins_nozomi__hikari-transformed.glb')
